### ISSUE TITLE
track used seed

### ISSUE THREAD

**Issue by sjanssen2** [jlab/marbel#16]
For data generation, it makes total sense NOT to fix random to a given seed. However, for debugging, it would be handy to know which actual seed has been used, such that one can recreate the simulation. Is there a way to obtain the seed python uses even if none is provided by the user? And if so, could you please report it here?

https://github.com/jlab/marbel/blob/4b11aa2b3da92f0e2e942b102a6de319f2d017f0/src/marbel/data_generations.py#L364

**Comment by tensulin** [comment]
Will do. It would be much easier to generate a random seed in the beginning and then give it to all libraries using random process. I will implement to like this
