### ISSUE TITLE
install as non root

### ISSUE THREAD

**Issue by sjanssen2** [jlab/marbel#9]
How can I install if on a machine without root permissions, e.g. in the BCF infrastructure?

`sudo apt-get install git-lfs`

**Comment by sjanssen2** [comment]
in the readme, the following line should also be set as a command:
`git clone https://github.com/jlab/marbel.git`

**Comment by tensulin** [comment]
I already asked Nils to install git-lfs on the cli machine, so its installed there. I just looked up and there is a conda recipe for git-lfs (conda install anaconda::git-lfs), not sure if something will break if this is used, I will test this and will update this in the ReadMe

**Comment by sjanssen2** [comment]
you give `marbel --n-species 30 --n-orthogroups 1500 --n-samples 15 20` as an example call. You might want to add `--outdir foo` to this call, such that the user will have all generated files in an predictable location.

What is the expected runtime? You might want to reduce numbers, if this takes > 5min OR add a smaller example in front of this one.

**Comment by tensulin** [comment]
It took 13m5.890s on Denbi de.NBI small 8 VCPUs - 16 GB RAM or 11m47.154s when i put in the correct threads, I will change it to a lower setting, the real example call is marbel without parameters as all parameters have default values
